### ISSUE TITLE
可选参数无效

### ISSUE THREAD

**Issue by zhuweitung** [wpscott/AcFunCard#1]
添加了参数`name_color=000000`，显示没有变化

建议再添加一个`粉丝数`这个文本类型的颜色设置参数

**Comment by zhuweitung** [comment]
再打开发现又有效了

**Comment by wpscott** [comment]
为了减少GitHub请求，设置了1小时缓存，所以可能不会实时更新。
粉丝数颜色等我从CJ回去更新。

**Comment by zhuweitung** [comment]
好的，祝CJ玩得开心，我已经退票了:(

**Comment by wpscott** [comment]
已更新
